#!/bin/sh
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pen stylus" MapToOutput HEAD-0
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pen eraser" MapToOutput HEAD-0
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 2 "key shift"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 3 "key ctrl"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 8 "key d"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 9 "key esc"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 1 "key ctrl s"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 10 "key left"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 11 "key right"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 12 "key PgUp"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 13 "key PgDn"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 15 "key l"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 16 "key ctrl l"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 17 "key a"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 18 "key x"
/usr/bin/xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 14 "key alt a"
