#!/bin/sh
xsetwacom --set "Wacom Cintiq 22HD Pen stylus" MapToOutput HEAD-0
xsetwacom --set "Wacom Cintiq 22HD Pen eraser" MapToOutput HEAD-0
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 2 "key shift"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 3 "key ctrl"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 8 "key d"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 9 "key esc"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 1 "key ctrl s"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 10 "key left"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 11 "key right"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 12 "key PgUp"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 13 "key PgDn"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 15 "key l"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 16 "key ctrl l"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 17 "key a"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 18 "key x"
xsetwacom --set "Wacom Cintiq 22HD Pad pad" Button 14 "key alt a"
