#!/bin/sh
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pen stylus" MapToOutput HEAD-0
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pen eraser" MapToOutput HEAD-0
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" MapToOutput HEAD-0
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Finger touch" MapToOutput HEAD-0
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Finger touch" Gesture off
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Finger touch" touch off
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" Button 2 "key esc"
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" Button 3 "key +d"
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" Button 1 "key alt a"
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" Button 11 "key up"
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" Button 13 "key down"
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" Button 12 "key left"
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" Button 10 "key right"
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" Button 8 "key ctrl z"
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" Button 9 "key ctrl shit z"