#!/bin/sh
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pen stylus" MapToOutput HEAD-0
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pen eraser" MapToOutput HEAD-0
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Pad pad" MapToOutput HEAD-0
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Finger touch" MapToOutput HEAD-0
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Finger touch" Gesture off
/usr/bin/xsetwacom --set "Wacom Cintiq 13HD touch Finger touch" touch off